export type RootStackParamList = {
  Home: undefined;
  CareerPlacement: undefined;
  CNATraining: undefined;
  Contact: undefined;
  Schedule: undefined;
  MentalHealth: undefined;
  About: undefined;
  Events: undefined;
  Profile: undefined;
  Mentorship: undefined;
  AnxietyResources: undefined;
  DepressionResources: undefined;
  CrisisHotlines: undefined;
  PeerPressure: undefined;
  SuicidePrevention: undefined;
  PhysicianMentorProgram: undefined;
  PurposeTechInstitute: undefined;
  CDLTrainingProgram: undefined;
  TestAuth: undefined;
  Login: undefined;
  SignUp: undefined;
  ForgotPassword: undefined;
  ProfileForm: undefined;
  CNAApplication: undefined;
  VideoQuizzes: undefined;
};
